### ISSUE TITLE
Feature Request: Manually inserting details

### ISSUE THREAD

**Issue by magnusburton** [BlinkTagInc/node-gtfs#102]
I'd like to request the possibility to manually insert details into, for example, my routes.txt file. My GTFS source lacks lots of details unfortunately so it'd be great if I could, say, add `route_color ` to specific routes.

`ADD route_color ='#FF00FF' WHERE route_id=1234ABC AND route_short_name=44`

I don't wanna have to do this manually because I'm importing a new GTFS file to my DB every day. What do you think of this idea?

**Comment by brendannee** [comment]
You could create a post import script that adds specific data into the database using mongo. You could use mongoose to insert these and actually use the models from node-gtfs: https://github.com/BlinkTagInc/node-gtfs/blob/master/models/gtfs/route.js

    var query = { route_id: '1234ABC' };
    Route.update(query, { route_color: '#FF00FF' }, callback)

Or better yet - try to reach out to the agency maintaining the GTSF and see if they will include the additional data in the feed.

**Comment by brendannee** [comment]
Closing this feature request - let me know if you have ideas on a better way to add details with a post-import script.
