### ISSUE TITLE
Hidden .git file after install

### ISSUE THREAD

**Issue by magnusburton** [BlinkTagInc/node-gtfs#107]
I’ve been having an issue with the latest releases. I’m receiving the error as I try to ‘npm i gtfs’:

node_modules/gtfs: Appears to be a git repo or submodule.

If I download the module directly from GitHub or npm the git file does not show up, only during install.

Try installing the module with npm and then run find ./ -name ".git" and to repro the issue.

The last working version were 1.8.2.
Thank you so much for an otherwise great module!

**Comment by brendannee** [comment]
Thanks for the detailed bug report.

Somehow a .git file got included in the npm package.

I removed it and published https://github.com/BlinkTagInc/node-gtfs/releases/tag/1.8.6 - try it out and let me know if this issue persists.
