### ISSUE TITLE
Feature Request: export GTFS from mongoDB

### ISSUE THREAD

**Issue by cptCloud** [BlinkTagInc/node-gtfs#110]
I know your lib is for importing and querying only. But if #102 is done, it would be great to be able to extract the GTFS from mongodb as a .zip file so it can be distributed. Agencies could then use your tool to perform quick updates on their GTFS.

**Comment by brendannee** [comment]
Great idea!

I added an export feature to version 1.10.0. Check it out and let me know what you think.
