### ISSUE TITLE
Update example code 

### ISSUE THREAD

**Issue by FredFronky** [BlinkTagInc/node-gtfs#112]
Hi there,
Been using this library for the past few days and been loving it so far. Just thought I'd raise this as an issue, as I've spent far too long trying to work it out.
The example code for simple setup has this line, which causes nodejs to raise deprecation warnings.
`mongoose.connect(config.mongoUrl, {useNewUrlParser: true});`
This is more of an annoyance than anything else at this point, but it might be worth updating the examples on the homepage to use the `mongoose.connect(config.mongoUrl, { useNewUrlParser: true, useCreateIndex: true, useUnifiedTopology: true });` variant from the gtfs-html example.

**Comment by brendannee** [comment]
Great point - I just updated the documentation with this info.

Thanks for the suggestion - let me know if you have any more.
