### ISSUE TITLE
script does not exit

### ISSUE THREAD

**Issue by sk92129** [BlinkTagInc/node-gtfs#114]
Hi 
I am new to nodejs -- but more familiar with GTFS data.
When I write and execute this script. it displays all the routes for a certain agency but does not exit.  It is "running" as if it is hung or waiting for something.

const gtfs = require('gtfs')
const mongoose = require('mongoose')
const config = require('./config/config.json')

mongoose.connect(config.mongoUrl, { useNewUrlParser: true, useCreateIndex: true, useUnifiedTopology: true })
  gtfs.getRoutes({
    agency_key: 'NYCSubway'
  }).then(routes => {
    //console.log(routes)
    console.log('Number of routes: '+ routes.length)
    routes.forEach(route => {
      console.log(route)}
    )    
    console.log('end of routes')
    
  });

console.log('end of app.js')

In my output and execute window, the 'end of app.js' is shown before all the routes are displayed.
After all the routes are displayed, I see 'end of routes' 
but the script has not exited.

What am I doing wrong?

I am a newbie to NodeJS and javascript.

**Comment by brendannee** [comment]
You'll want to call `process.exit()` in your `then` clause.

The `console.log('end of app.js')` gets called immediately because the `gtfs.getRoutes` method is asynchronous. You'll need to put anything you want to happen after all routes have been retrieved in the `.then` function.

Hope this helps!

**Comment by sk92129** [comment]
although this might help a utility script, exiting the process might not work if this is part of a whole nodejs RESTful server.
Invoking process.exit() might shut down the whole RESTful server application.

Is there a more specific exit for the request ?

**Comment by brendannee** [comment]
If you are running as a part of a server then you don't need to do anything - no need to exit. Just handle the routes in the .then function however you'd like.

**Comment by sk92129** [comment]
Cool. 
I get it now.  Thanks. I added in express and now it works well.

app.get('/routes', (request, response) => {
    if (!request.query.agency){
        return response.send({
            error: 'You must provide agency in url'
        })
    }
    console.log(request.query.agency)
    gtfs.getRoutes({
        agency_key: request.query.agency
      }).then(routes => {
        console.log('Number of routes: '+ routes.length)   
        response.send(routes)
      });    
})

**Comment by brendannee** [comment]
Great!

Let me know if you end up building something cool!

**Comment by sk92129** [comment]
Will do. 
I did a small show case of my project here (which is based on your component)  I will expand it further as I have time but wont publish all the features -- but just the starting point.
I did this to tickle my brain about nodejs -- I will eventually do some performance measurement to see how fast nodejs with this kind of data can be.  
https://github.com/sk92129/gtfsserver
