### ISSUE TITLE
No documentation for getFareAttributes

### ISSUE THREAD

**Issue by Abramovick** [BlinkTagInc/node-gtfs#116]
I don't seem to find documentation for `getFareAttributes()` on the docs. I can see `getFareRules()` but not `getFareAttributes()`. I know someone can just read the source code [here](https://github.com/BlinkTagInc/node-gtfs/blob/master/models/gtfs/fare-attributes.js) and see how it works, but it'd be nice to add it on the docs anyways since the functionality is there on the source code. I can raise a quick PR on the readme

**Comment by brendannee** [comment]
Good catch!  If you'd like to raise a PR to add it to the documentation that would be great!
