### ISSUE TITLE
Importing multiple feeds

### ISSUE THREAD

**Issue by donovanrichardson** [BlinkTagInc/node-gtfs#117]
I am new to this library, and I see that when it used mongo in the past, there was the option of querying by the `agency_key` set in the import. This doesn't look possible anymore, and when I try to query for the `agency_key`, I get this error:
```
Error: SQLITE_ERROR: no such column: agency_key
```

Additionally, when I try to import two different files, one will overwrite the other in the SQLite database. Is it possible to import two different gtfs feeds now, or would the SQL schema need to be changed to do this?

**Comment by brendannee** [comment]
Version 2.0 changed how data was stored and no longer users agency_key in the database.  Nearly all of the uses of this library revolve around dealing  with one agency at a time, so this greatly  simplified thiings.

One way to do deal with multiple agencies in version  2.0 is to make a config  file for each and specify a different SQLite database for each by using a different `sqlitePath` for each.

Can you let me know more about your use case around dealing with multiple agencies? Perhaps version 2.0 needs better support for dealing with multiple agencies in the same database.

**Comment by donovanrichardson** [comment]
I thought I had replied to this. But thanks for the suggestions! I'll probably end up using different configs. I was just curious.
