### ISSUE TITLE
transfers.txt default transfer_type

### ISSUE THREAD

**Issue by thekaveman** [BlinkTagInc/node-gtfs#121]
Hello @brendannee! I started poking around on [gtfs-to-geojson](https://github.com/BlinkTagInc/gtfs-to-geojson) again, with hopes of updating (and eventually archiving) [gtfs-service-area](https://github.com/cal-itp/gtfs-service-area).

I ran across an issue with interpretation of `transfers.txt`, specifically when the file has a missing `transfer_type` column. [The spec](https://developers.google.com/transit/gtfs/reference#transferstxt) is a little weird here, in that the field is marked **Required** but includes a default interpretation if empty!

> Indicates the type of connection for the specified (`from_stop_id`, `to_stop_id`) pair. Valid options are:
>
> `0` or empty - Recommended transfer point between routes.
> `1` - Timed transfer point between two routes. The departing vehicle is expected to wait for the arriving one and leave sufficient time for a rider to transfer between routes.
> ...

Seems [the model has that field marked as required](https://github.com/BlinkTagInc/node-gtfs/blob/master/models/gtfs/transfers.js#L24).

An example feed that will trigger an import error is [Big Blue Bus as of Feb 09, 2021](https://github.com/BlinkTagInc/node-gtfs/files/5954787/bigbluebus-20210209.zip).

**Comment by brendannee** [comment]
Great catch - I just published a new version of node-gtfs 2.4.1 which changes this to not required (since it is effectively not required to have a value).

I also pulled this into a new version of  gtfs-to-html 2.0.5 so you should be good to go.

**Comment by thekaveman** [comment]
Yes! Thanks for the update!
