### ISSUE TITLE
Typescript Support for node-gtfs

### ISSUE THREAD

**Issue by samridhgupta** [BlinkTagInc/node-gtfs#123]
Have a Typescript Express Server for consuming GTFS data.

But due to no TS support I m facing this error
```Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: <Project-path>/node_modules/gtfs/index.js
require() of ES modules is not supported.
require() of <Project-path>/node_modules/gtfs/index.js from <Project-path>/src/index.ts is an ES module file as it is a .js file whose nearest parent package.
json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from <Project-path>/node_modules/gtfs/package.json.
````

Using it this way
`import { importGtfs } from 'gtfs';`

Found a type Library for GTFS 
https://www.npmjs.com/package/gtfs-types
But unable to  find a solution to include these types to the Project

**Comment by brendannee** [comment]
Thanks for letting me know about this issue.

* This post https://dev.to/asteinarson/typescript-nodejs-and-es6-esm-modules-18ea suggests that you could use the 'esm' node module to "require" the library: https://www.npmjs.com/package/esm

* You could just use version 2.x of node-gtfs which is written as a commonjs module: https://github.com/BlinkTagInc/node-gtfs/releases/tag/2.4.4

* You could update your project to be an es module: set the "type" property in package.json to "module" and then do all needed syntax updates: https://ar.al/2021/01/27/commonjs-to-esm-in-node.js/

* There could be some typescript tsconfig.json settings which allow you to use esmodules: https://fettblog.eu/typescript-and-es-modules/


Let me know if you figure out a way to use this.

**Comment by DarkMatterMatt** [comment]
I made some basic typings, https://gist.github.com/DarkMatterMatt/7c66929a337236d04eca752620a20650. They're not perfect yet, I'll add them to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) when they've been tested for a bit.

**Comment by brendannee** [comment]
Looking good - what is the best way to integrate these into this repo?

**Comment by brendannee** [comment]
Thanks for this - I merged in the typescript PR and created a new version 3.2.0 which has this and multiple database support.

Try it out and let me know what you think.

More PRs and issues welcome if you find anything else that needs to be updated or have ideas for additional features.
