### ISSUE TITLE
GTFS Fares V2

### ISSUE THREAD

**Issue by Abramovick** [BlinkTagInc/node-gtfs#131]
Hi there,
I'm tryna implement GTFS fares v2 and load it into my database using node-gtfs. But i can see that some of my files such as `fares_legs_rules.txt` are not being imported into the database at all.

Any advice on that?

**Comment by brendannee** [comment]
Thanks for the note.

I added all of the files and fields for GTFS fares v2 in the 3.6.0 release just published.

Try it out and let me know if there are any issues.
