### ISSUE TITLE
[Feature Request] Create option to ignore SSL validation 

### ISSUE THREAD

**Issue by yalihart** [BlinkTagInc/node-gtfs#135]
The GTFS URL provided by my local agency has SSL issues. I tried messaging them about but they don't seem to care. Can you add a feature to ignore SSL validation when fetching from a URL?

**Comment by brendannee** [comment]
You could try setting 

```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
```

in your script before running node-gtfs.  You may want to unset this afterwards as it disables SSL validation everywhere.

Alternatively, your script  could handle the download of the GTFS (ignoring SSL validation) and then save the GTFS to a directory. Then just specify that path to node-gtfs to use locally.

Do either of these workarounds solve the issue?

**Comment by brendannee** [comment]
If you find the best way to implement this that works with your use case (see here https://github.com/BlinkTagInc/node-gtfs/blob/1f3e70e7be0811742f211ea725b01f36bcf55e7d/lib/import.js#L35 ) please make a pull request so I can check it out.

This approach https://stackoverflow.com/a/59944400/363155 might be a good place to start.
