### ISSUE TITLE
Can I use the command line for query operations?

### ISSUE THREAD

**Issue by MineRiaaa** [BlinkTagInc/node-gtfs#136]
I wonder how to use the command line to execute query operations. The README.md didn't mention it.

**Comment by brendannee** [comment]
Great question. 

After importing your GTFS, you can use `sqlite3` from the command line to execute queries.

```
sqlite3 /tmp/gtfs "select * from trips;" ".exit"
```

Would it be useful to have a command within the GTFS library to do this?  Like:

```
gtfs query "select * from trips;"
```

**Comment by MineRiaaa** [comment]
I'm sorry I didn't make my question clear, but still thank you for your answer, which is also very helpful to me.
Below is the detailed description of my question:
I am using Windows, and I want to test the query methods and query efficiency of NODE-gtfs. However, I don't have a specific project, so I choose to implement this library with the command line. I hope I can use the command line to implement the **Query Methods** mentioned in the documentation, such as _getRoutes()_ and _getStops()_, etc.
Do I need to write a js file and run it from the command line?

**Comment by brendannee** [comment]
Thanks for clarifying.

You are correct that in order to use the query methods from the command line, you'll need to make a js file that implements them.  

You can see some small example scripts here: https://github.com/blinktaginc/node-gtfs#examples

You'll need to create a package.json file and install 'gtfs' from npm too.

Let me know how it goes.

**Comment by MineRiaaa** [comment]
Thanks a lot! 

I'll have a try and show the results here.

**Comment by MineRiaaa** [comment]
It works!

I created a _getStops.js_ file and a  _config.json_ file under the GTFS folder.

The code of _getStops.js_ is as follows:

`import { openDb, getStops } from '../gtfs/index.js';
import { readFile } from 'fs/promises';

const config = JSON.parse(await readFile(new URL('./config.json', import.meta.url)));

const db = openDb(config);
const stops = getStops(
  {
    stop_id: [
      '1622',
      '5182'
    ]
  }
);
console.log(stops);`

Then I ran the command:

`node getStops.js`

The results are printed:

`[
  {
    stop_id: '1622',
    stop_code: '1014',
    stop_name: 'Pacheco Blvd + Arthur Rd',
    tts_stop_name: null,
    stop_desc: null,
    stop_lat: 38.00626,
    stop_lon: -122.090569,
    zone_id: null,
    stop_url: null,
    location_type: 0,
    parent_station: null,
    stop_timezone: null,
    wheelchair_boarding: 2,
    level_id: null,
    platform_code: null
  },
  {
    stop_id: '5182',
    stop_code: '1162',
    stop_name: 'Lafayette BART',
    tts_stop_name: null,
    stop_desc: null,
    stop_lat: 37.893571,
    stop_lon: -122.125128,
    zone_id: null,
    stop_url: null,
    location_type: 0,
    parent_station: null,
    stop_timezone: null,
    wheelchair_boarding: 2,
    level_id: null,
    platform_code: null
  }
]`

**Comment by brendannee** [comment]
That is great - thanks for sharing your working code.
