### ISSUE TITLE
GTFS-R TripDescriptor

### ISSUE THREAD

**Issue by stephenmcbride** [BlinkTagInc/node-gtfs#137]
Hi, apologies if this is the wrong place to post this but I'm trying to identify how the [TripDescriptor](https://gtfs.org/realtime/feed-entities/trip-updates/#tripdescriptor) is used (or perhaps it's not?) when fetching GTFS-R trip updates data using node-gtfs. I was expecting to see a similarly named field within the trip_updates table but there is no sign of it. It seems as far as I can understand that without TripDescriptor there is no way of knowing if a trip has been canceled - but perhaps I'm wrong? 

Any help much appreciated!

**Comment by brendannee** [comment]
Thanks for pointing this out - currently the library doesn't save TripDescriptor to the database.   I'll work on getting this added.

**Comment by stephenmcbride** [comment]
Thank you! 👍

**Comment by jhruzova** [comment]
Hi, may I ask, how is this feature improvement going? It would be great to have TripDescriptor in trip_updates to recognize if the trip was canceled. :)

**Comment by brendannee** [comment]
I updated the GTFS-Realtime importing feature to include schedule_relationship fields in the `trip_updates` and stop_time_updates` tables, so you can now tell if a trip is:
* SCHEDULED
* ADDED
* UNSCHEDULED
* CANCELED

Additionally, these tables now have fields for `trip_start_time`, `direction_id` and `route_id`.

Check out the latest version and let me know if this has everything needed.

**Comment by jhruzova** [comment]
Yes, thanks a lot! 👍
