### ISSUE TITLE
Dropping/Clearing database

### ISSUE THREAD

**Issue by Technerder** [BlinkTagInc/node-gtfs#139]
Is it possible to clear the database (default in memory)? I'm looking to have a long running node process which needs to access numerous different GTFS feeds sequentially and don't want to run into conflicts with different feeds being leftover at the same time. Is this possible?

**Comment by brendannee** [comment]
Good question:

You can use `closeDb(db)` to close the connection to the database, and then use `openDb` again which should create a new in-memory database. I updated the readme to include some more details on this method: https://github.com/BlinkTagInc/node-gtfs#database-setup

Let me know if that works in clearing the database.
