### ISSUE TITLE
Deployment on errors

### ISSUE THREAD

**Issue by Abramovick** [BlinkTagInc/node-gtfs#141]
Hi when i try to run/deploy the project in some unix environment i get 
```
Importing GTFS from /var/folders/qp/hcfq2x1x66x64z6n54x6sr6r0000gn/T/tmp-47953-kWDhOyCFUIVQ/gtfs.zip

Error: More than one subfolder found in zip file at `/var/folders/qp/hcfq2x1x66x64z6n54x6sr6r0000gn/T/tmp-47953-kWDhOyCFUIVQ/gtfs.zip`. Ensure that .txt files are in the top level of the zip file, or in a single subdirectory.

[  Error: More than one subfolder found in zip file at `/var/folders/qp/hcfq2x1x66x64z6n54x6sr6r0000gn/T/tmp-47953-kWDhOyCFUIVQ/gtfs  .zip`. Ensure that .txt files are in the top level of the zip file, or in a single subdirectory.
```

It happens when loading by URL. It seems like the issue is with unzipping the zip file.
Any idea how to fix this?

**Comment by brendannee** [comment]
You can download the zip file, unzip it manually and then use the `path` config argument to point to the directory where it is unzipped.

**Comment by Abramovick** [comment]
Here it is: https://safiri.s3.eu-west-2.amazonaws.com/safiri_tz_rgn_final.zip

**Comment by Abramovick** [comment]
Hi Brendan,
Thanks for your help.

Here it is:
https://safiri.s3.eu-west-2.amazonaws.com/safiri_tz_rgn_final.zip

**Comment by brendannee** [comment]
I see that this zip file has a hidden __MACOSX folder in it in addition to a folder with the GTFS.

I pushed an updated version of GTFS-to-HTML that will ingnore this type of system folder within zip files - try version https://github.com/BlinkTagInc/gtfs-to-html/releases/tag/2.5.3 and let me know if you have any issues.
