### ISSUE TITLE
Invalid default csv parser option "relax" in import script.

### ISSUE THREAD

**Issue by david-abell** [BlinkTagInc/node-gtfs#142]
I discovered while troubleshooting a lack of leading "0" on timestamp fields such as `"stop_times"."arrival_time"` ie. `6:31:00` instead of `06:31:00` that the "relax" option is no longer a valid csv parser option, [code here](https://github.com/BlinkTagInc/node-gtfs/blob/7e22e5b0c4201e50e0fd11bb2605f6033dbfc205/lib/import.js#L533).

According to [this issue](https://github.com/adaltas/node-csv/issues/297#issuecomment-1060880543), it is probably meant to be `"relax_quotes"`. Csv parse doesn't throw an error for this change so that's probably why it slipped through.

For reference [here's the current csv parse option types](https://github.com/adaltas/node-csv/blob/22f4017e01e41572ca8cb8d4b19321f9a9b34288/packages/csv-parse/lib/index.d.ts#L167)

The leading zero issue turned out to be a problem with my data source, easily fixable with an additional import helper function. I'd be happy to submit a separate issue with my sample code if that is within this project's scope.

**Comment by brendannee** [comment]
Thanks for the detailed notes.

I updated the parsing options to "relax_quotes" and published an updated version: https://github.com/BlinkTagInc/node-gtfs/releases/tag/4.3.2 Let me know if that solves the issue. 

As for handling the lack of leading "0" on timestamp, it would be great to have your sample code to review and include - this library should support GTFS without leading "0"s. Please open a new issue with your code, or a PR if you prefer.

**Comment by david-abell** [comment]
You are welcome @brendannee, Sounds good! I've created a small pull request.
