### ISSUE TITLE
Changing internal maxInsertVariables has significant impact on total import time

### ISSUE THREAD

**Issue by david-abell** [BlinkTagInc/node-gtfs#149]
I discovered while writing my own version of an import script and using this project as a comparison that `const = maxInsertVariables` used in this library [here](https://github.com/BlinkTagInc/node-gtfs/blob/886c4ad805290afe25d955aa80045e00bcf09d5e/lib/import.js#L536C7-L536C7) has a significant effect on total import time. The dataset I'm working with has around 13M records [tested with a fairly recent download from here](https://www.transportforireland.ie/transitData/Data/GTFS_All.zip) so cutting down time is pretty important.

I haven't done a ton of testing for possible values (only got so much patience for watching numbers tick up) but as you can see below, the default 800 seems a little cautious. For my dataset and current hardware, at least, the sweet spot is quite a bit higher.

- maxInsertVariables = 800 records default - pass 1 = 1087 seconds, pass 2 = 1168 seconds
- maxInsertVariables = 8_000 records -  pass 1 = 519 seconds pass 2 = 501 seconds, pass 3 = 499
- maxInsertVariables = 20_000 records - pass 1 = 382 seconds, pass 2 = 411 seconds, pass 3 = 414
- maxInsertVariables = 30_000 records - pass 1 = 402 seconds, pass 2 =396 seconds
- maxInsertVariables = 40_000 SQL Error: too many variables

I'm also no database expert so there might be other impacts beyond this that have led to maxInsertVariables being 800? If its system specific maybe it makes sense to expose the variable as part of the config options?

**Comment by david-abell** [comment]
@matthiasfeist I just noticed you were looking at performance with some large file imports. I don't know how it compares to the performance you are seeing with DuckDb, but this might interest you as an alternative.

**Comment by brendannee** [comment]
Thanks for these details and tests.

It looks like sqlite3 recently changed the default SQLITE_MAX_VARIABLE_NUMBER from 999 to 32766. I released node-gtfs version 4.5.0 which increases the limit to 32_000 variables per insert with a substantial performance improvement!

Let me know how it works for you and if there are any other updates or suggestions that you have.

**Comment by matthiasfeist** [comment]
this is awesome. DuckDB still seems a bit faster but for my usecase now the speed increase is actually good enough so I'm gonna drop all my fiddling around with a different solution :)

**Comment by matthiasfeist** [comment]
I've done a comparison now between the current state of node-gtfs and a simple import via DuckDB: https://github.com/BlinkTagInc/node-gtfs/issues/148#issuecomment-2250635811
