### ISSUE TITLE
Agency_id defined in agency.txt but not in routes.txt results in invalid GTFS export

### ISSUE THREAD

**Issue by brodyFlannigan** [BlinkTagInc/node-gtfs#151]
Hi! I can't believe I'm just discovering node-gtfs now. Been using GTFS-to-HTML for years. Had no idea how amazing this is.

I've just discovered a bit of an issue with gtfs-export in a bit of a niche edge case.

The [STO's GTFS](https://contenu.sto.ca/GTFS/GTFS.zip) provides an agency_id ("STO") in agency.txt. However, in routes.txt, since there's only one agency in the whole feed, they don't provide agency_id in routes.txt. According to the spec, this is allowed.

However, what results when using gtfs-export is the agency_id in agency.txt being populated with "STO", but the agency_id in routes.txt being populated with "null". Since those two values are not the same, the exported GTFS is invalid.

The ideal solution would be to check on import if agency_id is defined on the route level, and if it isn't, define it based on agency.txt or something.

Would it be possible to look into this?

Thanks!

**Comment by brendannee** [comment]
I'm glad it is a useful library for you.

This is a great catch - I pushed an update that I think will solve this issue by excluding the agency_id field entirely from routes.txt when exporting if it is blank for all routes.

https://github.com/BlinkTagInc/node-gtfs/releases/tag/4.5.1

Let me know if this solves the issue for you.
