### ISSUE TITLE
occupancyStatus from vehicle_positions

### ISSUE THREAD

**Issue by nukeador** [BlinkTagInc/node-gtfs#159]
Hi there,

Thanks for the great project!

I'm struggling to find how can I query for the occupancyStatus field from vehicle positions realtime feed. I don't see it as a field being imported in the SQLite, so not sure if fetching this field is not supported or I don't know how to query it.

Thanks!

**Comment by nukeador** [comment]
Hi,

I updated the package from 4.5.1, and I noticed at 100x slowness in recurrent queries for my app, so I'll need to check more carefully what's going on.

Are there important changes since that version that might be impacting performance?

**Comment by nukeador** [comment]
Nevermind, for some reason my system got hanged, not related with node. It seems the Occupancy data is showing on the sqlite, thanks so much!

**Comment by brendannee** [comment]
Let me know what other fields are missing from the GTFS-realtime import or
if there are any that are awkwardly named or not working as expected.

**Comment by nukeador** [comment]
I guess the only ones missing from VehiclePositions data can be these:

https://gtfs.org/realtime/feed-entities/vehicle-positions/#vehicledescriptor

**Comment by brendannee** [comment]
Good call.

I pushed a commit that includes the fields from vehicle descriptor - these will be added to the next release.
