### ISSUE TITLE
Deleting the db to avoid id collisions

### ISSUE THREAD

**Issue by laem** [BlinkTagInc/node-gtfs#161]
Hi, I was confronted with a weird problem : while analysing routes for their frequency, I got strange results : a suppposedly school bus was apparently running on sundays. 

Turns out, it was a db update problem : the GTFS I was loading every day was updated reusing serviceIds that were used by totally different routes. 

My simple solution is to delete the DB. Maybe this could be a feature ? 

Right now, I'm calling the DB "2024-05-12-11-14" (day hour minutes) and removing them after a successful update.

**Comment by brendannee** [comment]
If you leave the config sqlitePath empty, an in memory database will be
used. This will be deleted as soon as the process is complete.

Would that solve the problem you describe?

**Comment by laem** [comment]
Not really, because I want to store the database in the filesystem to avoid reparsing the GTFS if the server crashes (or in dev mode, when I restart my server after a change).

**Comment by brendannee** [comment]
Check out the latest version https://github.com/BlinkTagInc/node-gtfs/releases/tag/4.10.3 - I added a deleteDb method: https://github.com/BlinkTagInc/node-gtfs?tab=readme-ov-file#deleting-a-database

Let me know if this doesn't work for your use case.
