### ISSUE TITLE
Zip File Containing Multiple GTFS Static Zip Files

### ISSUE THREAD

**Issue by mark1foley** [BlinkTagInc/node-gtfs#165]
Some agencies publish multiple GTFS static zip files as single zip file (e.g. [Vicroads](https://data.ptv.vic.gov.au/downloads/gtfs.zip) and [Septa](https://www3.septa.org/developer/gtfs_public.zip)).  Unfortunately, they don't appear to provide an option to download the individual zip files.  
For these agencies I can manually download the zip file, extract the GTFS static zip file that I'm interested in and then pass this to gtfs-import?  However, I was hoping there may be some way of having gtfs-import download the zip file using the URL and specifying which folder within the zip to use.  I have looked through the options and can't see anything but just thought I would ask.

**Comment by brendannee** [comment]
The GTFS working group updated their list of requirements, and one of the more recently updated requirements is that GTFS files must be in the root level directory: 

"All dataset files must be zipped together. The files must reside at the root level directly, not in a subfolder."

https://gtfs.org/schedule/reference/#dataset-files

So, according to this, these agencies are not publishing valid GTFS if the zip file contains subfolders and multiple different GTFS files. (you could let them know about this and maybe they will update their publishing process)

However, as a workaround, I suggest adding a preprocessing script that downloads the zip file, unzips it to a specified directory and then run node-gtfs with the configuration set to the unzipped path. node-gtfs doesn't require that local files be zipped, the path to unzipped GTFS files works just fine.

Alternatively, you could fork node-gtfs and add logic to unzip the downloaded file and specify the `task.path` variable to the unzipped directory here: https://github.com/BlinkTagInc/node-gtfs/blob/master/lib/import.js#L33

**Comment by mark1foley** [comment]
Thank you for the detailed reply.  Much appreciated.

**Comment by brendannee** [comment]
Let me know how you end up solving this or if you have other ideas on how node-gtfs could be improved.

Are you setting up a system to automatically fetch GTFS?

I'd be interested in documenting patterns for pre-processing and post-processing GTFS before/after it is handled by node.js.
