### ISSUE TITLE
ignoreErrors to ignore only the failing url/path

### ISSUE THREAD

**Issue by nukeador** [BlinkTagInc/node-gtfs#168]
Right now "ignoreErrors": true will skip the import of the whole agency even if only one realtime URL is failing.

Probably it should skip only the import of the failing component?

For example, a fail in the alert URL shouldn't skip the rest of the RT URLs.

**Comment by brendannee** [comment]
Thanks for pointing this out.

When I tested the latest version of node-gtfs, it actually does handle skipping only the failed URL. I tried making the GTFS-realtime alerts URL invalid and it successfully imported trip updates and vehicle positions.

Let me know if this doesn't seem to be the case for you.

**Comment by nukeador** [comment]
The error is only ignored when doing `gtfs.importGtfs()`, when doing `gtfs.updateGtfsRealtime()` the ignore error doesn't seem to be handled:

```
Downloading GTFS-Realtime from http://thisdoesnotexist/api/alertError de red al actualizar los datos GTFS en tiempo real: Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

**Comment by brendannee** [comment]
Yes - you are right!

I pushed an update that should make the gtfs.updateGtfsRealtime() function work the same way as gtfs-importGtfs() https://github.com/BlinkTagInc/node-gtfs/releases/tag/4.14.3

Let me know if this doesn't work as expected.

Thanks a lot for finding and reporting this issue.

**Comment by nukeador** [comment]
Thanks, the error is now ignored but still I can't manage to get the rest of the valid realtime urls to be updated/imported.

This is my config, the alerts url is the one failing, I get `Error: fetch failed` when doing `gtfs.updateGtfsRealtime()` but also trip updates and vehicle positions tables on the SQLite are empty, so I assume the update fails for all URLs and not just the wrong one.

```
"realtimeAlerts": {
        "url": "http://thisdoesntexist/alert",
      },
      "realtimeTripUpdates": {
        "url": "http://212.170.201.204:50080/GTFSRTapi/api/tripupdate",
      },
      "realtimeVehiclePositions": {
        "url": "http://212.170.201.204:50080/GTFSRTapi/api/vehicleposition",
      }
```

**Comment by brendannee** [comment]
Good catch - I wasn't testing with a completely invalid URL and so wasn't seeing the same thing.

Check out this released - I think this issue is resolved https://github.com/BlinkTagInc/node-gtfs/releases/tag/4.14.4

Additionally, downloads for multiple agencies happen in series to make it easier to troubleshoot if you don't have ignoreErrors: true set.

**Comment by nukeador** [comment]
Working great now, thanks so much for your time!
