### ISSUE TITLE
TypeScript support for `fields` parameters

### ISSUE THREAD

**Issue by b-e-b-o-o** [BlinkTagInc/node-gtfs#174]
Currently there are two type-related issues with using `fields` for filtering returned columns in query functions:

1. There is no IntelliSense on which columns are available
2. The return type is (an array of) the full base type, regardless of whether we have filtered it or not.

I propose the following fix:

1. For IntelliSense on in, you can add a type parameter to query function declarations:

    ```js
    export function getStoptimes<Fields extends keyof StopTime>(
      query: SqlWhere = {},
      fields: Fields[] = [],
      orderBy: SqlOrderBy = [],
      options: QueryOptions = {},
    ): StopTime[] { ...
    ```

2. For the return value, you can use a reusable generic type like this:

    ```js
    type ReturnType<Base extends object, Fields extends keyof Base> =
      [Select] extends [never]
      ? Base
      : Pick<Base, Fields>;
    ```
    
    The `[Select] extends [never]` condition ensures that when `fields` is an empty array, the original type is used as the return type.
    
    To complete the function declaration:
    
    ```js
    export function getStoptimes<Fields extends keyof StopTime>(
      query: SqlWhere = {},
      fields: Fields[] = [],
      orderBy: SqlOrderBy = [],
      options: QueryOptions = {},
    ): ReturnValue<StopTime, Fields>[] { ...
    ```
    
    And of course, add it to the function's return as well:
    
    ```js
    return ... as ReturnType<StopTime, Fields>[];
    ```

In the future it would be nice to have better type support for other parameters as well, most importantly for `query` (which should be pretty simple, but this is all the time I had right now).

*Ps. These codeblocks might appear strange, I'm using js syntax highlighting because apparently ts highlighting is goofy in github's markdown*

**Comment by MicrosoftEggshell** [comment]
If I find some more time I could look into writing a regex search&replace for this and open a PR, it shouldn't take too long and it's certainly better than doing it manually...

It *is* this simple, right?

**Comment by MicrosoftEggshell** [comment]
Apparently my `ReturnType` does not work for when `fields` is explicitly specified to be `[]`... Look, I'm not a TypeScript wizard, I'm just doing my best here. I'll look for a fix.

**Comment by brendannee** [comment]
Thanks for the PR. 

See the latest release https://github.com/BlinkTagInc/node-gtfs/releases/tag/4.15.6 and let me know if there are any issues or other improvements to make.
