### ISSUE TITLE
Adding a prefix results in foreign key violations

### ISSUE THREAD

**Issue by brodyFlannigan** [BlinkTagInc/node-gtfs#176]
Hello!

When the config file specifies a prefix to be added on data import, when a foreign key reference is left blank in the GTFS data, the record is populated with `{prefix}null`

For instance, if a stops.txt record doesn't include the level_id field, or it's left blank by the data producer for a given record, it appears in the database (and in GTFS exports) with the prefix followed by "null".

This issue seems to exist for all the GTFS fields that reference an ID from another table (for instance, `to_route_id` and `from_route_id` in transfers.txt, `zone_id` in routes.txt, and many, many other fields.

The expected behaviour would be that if a field is left empty or not provided in the source data, it should be left full blank/empty in the database and in the exported data.

Could this be looked into?

Thanks!

**Comment by brendannee** [comment]
Good catch - thanks for finding this.

See the latest version https://github.com/BlinkTagInc/node-gtfs/releases/tag/4.15.5 which should resolve this issue.

Try it out and let me know if there are still any issues.

**Comment by brodyFlannigan** [comment]
Works like a charm. Thanks for the super quick fix!
