### ISSUE TITLE
fare_products doesn't respect ISO 4217 decimal places requirement for amount

### ISSUE THREAD

**Issue by brodyFlannigan** [BlinkTagInc/node-gtfs#177]
Hi,

The GTFS spec [indicates ](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#field-types) that for fields of the `Currency amount` type, the number provided must have the appropriate number of decimal places as specified by [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217#Active_codes).

For instance, if a fare_product is given in CAD (Canadian Dollars), per ISO 4217, two decimal points should be given, so if the rider must pay $5, the `amount` value should be `5.00`. However, currently, the GTFS export functionality does not respect this, and "redundant" zeroes are removed. For instance, in the example given above, the exported GTFS has an amount of `5`. 

The issue also exists when there are decimals, but ending in zero. For instance, a fare product with an amount of `5.20` will be exported as `5.2`

You can use the [Transcollines Fares GTFS](https://github.com/transcollines/GTFS/raw/refs/heads/master/transcollines-qc-ca-fares.zip) to see this issue.

Thanks!

**Comment by brendannee** [comment]
Great catch.

I updated the export function so that the correct number of decimals based on the currency will be included in the export file, regardless of if they are all zeros.

See this release https://github.com/BlinkTagInc/node-gtfs/releases/tag/4.15.8

**Comment by brodyFlannigan** [comment]
Thanks for looking into this so quickly.

Unfortunately, the issue doesn't seem resolved.

I'm running this INSERT query on my database:

```
INSERT INTO fare_products (fare_product_id, amount, currency)
VALUES ('PS-500', 5.00, 'CAD')
```

But I'm still getting this when I run the export afterwards...

```
fare_product_id,fare_product_name,fare_media_id,amount,currency
PS-500,,,5,CAD
```

When I look in the SQLite database, I can see the number stored as "5".

**Comment by brendannee** [comment]
Ah - I pushed a fix for that https://github.com/BlinkTagInc/node-gtfs/releases/tag/4.15.9 (wrong column name for fare_products).

Try that out and let me know if it works for you.

**Comment by brodyFlannigan** [comment]
Works great! 

Thanks again for these quick fixes. It's so appreciated.
