### ISSUE TITLE
getRoutesByDistance is returning data from other agencies

### ISSUE THREAD

**Issue by mrajabtech** [BlinkTagInc/node-gtfs#68]
I tried to pull routes somewhere in Melbourne within a mile radius. 

eg. http://loc.iamraja.com:8000/getRoutesByDistance?lat=-37.866612&lon=144.993121&radius=1

But the script returned data including routes from other agencies too(Adelaide, Perth etc). I think this because the route query is not supplied with **agency_id**

Please let me know if you need any more info.

**Comment by brendannee** [comment]
Hi,

This method was designed to do just that - get all routes across agencies within a specific distance. I think maybe we need to introduce an optional `agency_key` and `agency_id` parameter to support what you want to do. Until that gets added, you'll have to get all routes and then filter out the ones you don't want by `agency_id`
