### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by arctouch-douglaskazumi** [BlinkTagInc/node-gtfs#70]
I'm using the following code to try to get the Caltrain data. Apparently, it works but when checking the data I've noticed that something went wrong. Checking the raw `stops` file I see 31 stops with `platform_code` as `NB` and 31 as 'SB'. After importing and querying, I see 31 and 33, respectively.
The 2 extra stops for `SB` are 2 stations that don't have a value for `platform_code` in the raw file and somehow it's defaulting to `SB`.

``` js
"use strict";

const mongoose = require('mongoose');
const gtfs = require('gtfs');
const config = {
  mongoUrl: 'mongodb://url',
  agencies: [{
    agency_key: 'Caltrain',
    url: 'http://www.caltrain.com/Assets/GTFS/caltrain/CT-GTFS.zip',
    exclude: [
      'shapes'
    ]
  }]
};

module.exports = {
  updateData: updateData
};

function updateData(req, res) {
  mongoose.Promise = global.Promise;
  mongoose.connect(config.mongoUrl);
  gtfs.import(config, (err) => {
    res.json({
      result: err || "Success"
    });
  });
}
```

**Comment by brendannee** [comment]
I checked the GTFS file at http://www.caltrain.com/Assets/GTFS/caltrain/CT-GTFS.zip - the current version there actually has 31 NB stops and 33 SB stops,

Can you check the file you are importing again?

**Comment by arctouch-douglaskazumi** [comment]
So, they've recently updated their files. Please find attached the files I've originally used.
[CT-GTFS.zip](https://github.com/BlinkTagInc/node-gtfs/files/904191/CT-GTFS.zip)

**Comment by brendannee** [comment]
Give this a try with the new node-gtfs 1.0.0 and let me know if you still see anything inconsistent. There have been changes and improvements which may have solved this issue.
