### ISSUE TITLE
getStoptimesByStop hangs and return neithers times nor error(s)

### ISSUE THREAD

**Issue by W3stside** [BlinkTagInc/node-gtfs#71]
Hi guys - noticed a bug with getStoptimesByStop while testing. Running latest Chrome and testing on both local MongoDB via node but also a heroku dev server + GLITCH. Both environments fail. Query tested:

<h3>My Query:</h3>

    gtfs.getStoptimesByStop ( 'myAgencyNameHere' , 'LA' , 'ETOILE' )
        .then(stoptimes => {
            console.log(stoptimes);
         }

All arguments here are made up for this example but my actual values were verified. Issue here is that nothing gets returned. No stop times and no error(s). Honestly no idea why it hangs.

Checked the source code and located the error within **/lib/gtfs/stop-times.js** - the first Promise does not pass the "Pending" stage.

<h3> Original: </h1>

```
exports.getStoptimesByStop = (agencyKey, routeId, stopId, directionId, cb) => {
  if (_.isFunction(directionId)) {
    cb = directionId;
    directionId = undefined;
  }
  return new Promise(() => {
        if (agencyKey === undefined) {
          new Error('No agencyKey specified');
        } else if (stopId === undefined) {
          new Error('No stopId specified');
        } else if (routeId === undefined) {
          new Error('No routeId specified');
        }
  })

```

<h3>My changes:</h3>
<ul>
<li>Removed empty promise</li>
<li>Passed back in resolve and reject</li>
<li>added reject cases</li>
<li>removed the cb and added a catch(err) at the bottom for err trace</li>
</ul>

```
exports.getStoptimesByStop = (agencyKey, routeId, stopId, directionId, cb) => {
  if (_.isFunction(directionId)) {
    cb = directionId;
    directionId = undefined;
  }
  return new Promise((resolve, reject) => {
    if (agencyKey && routeId && stopId) {
      resolve ();
    } else {
        if (agencyKey === undefined) {
          reject( new Error('No agencyKey specified') );
        } else if (stopId === undefined) {
          reject ( new Error('No stopId specified') );
        } else if (routeId === undefined) {
          reject ( new Error('No routeId specified') );
        }
      }
  })

// skipping to end of stack ...

.catch (err => {
    console.log(err);
}

```
<h3>And so</h3>
Query now works - returns errors and error traces as well.

Also... this is my first issue report on Git so I apologize for anything incorrect - tried to be as helpful as possible. If this change ends up being useful, could I submit a PR and submit? That too would be my first!

And obviously, thanks so much for the project.

**Comment by timothyleung** [comment]
Having the same problem. The query returns nothing.

**Comment by timothyleung** [comment]
I looked in deeper and realise what I got is actually "No times available for this stop on this date", so I guess the Error was catched by some function and did not return to the main routine. 

Should we return an empty list instead of throwing errors in this case? 

Because in my case, I have not integrate real-time gtfs yet. The bus stop I was using is temporary closed. So it exists in stops.txt and I can also find the route ID. However, this stop and this route has changed since the bus stop is closed.

Please let me know if I am not querying in the right order.

**Comment by brendannee** [comment]
Thanks for reporting this. Your proposed fix was exactly what was needed to fix this method.

I published a new release with this fix.

This method isn't one of the best ones - as you may have seen it just uses todays date to look up service_ids for the specified stop. Ideally, it shoudl take service_ids as an argument - so I may modify how this works in a future release.
