### ISSUE TITLE
Error: Cannot find configuration file at... Use config-sample.json as a starting point, pass --configPath option

### ISSUE THREAD

**Issue by russellhoff** [BlinkTagInc/node-gtfs#73]
I'm having some trouble while trying ti import a GTFS to my database.... Here you are what happens:

`Error: Cannot find configuration file at `D:\workspace-node\node-gtfs\config.json`. Use config-sample.json as a starting  point, pass --configPath option`

![image](https://cloud.githubusercontent.com/assets/1479066/25889015/a8b525a0-3568-11e7-8525-49efb64cd7ac.png)

**Comment by russellhoff** [comment]
Just to note that this error doesn't happen in gtfs-to-html

**Comment by brendannee** [comment]
I haven't used this on windows, so perhaps there is an issue with the way paths are handled.

I did review the import path processing function and found some issues, so I pushed an update with some fixes: https://github.com/BlinkTagInc/node-gtfs/commit/447b1ee4a67f3676b17c8de41fbc3d0416d2ba60

Try the latest version 0.9.11 and see if that solves this issue.

**Comment by brendannee** [comment]
Closing this issue - @russellhoff please reopen or comment if you are still having the same problems.
