### ISSUE TITLE
skipDelete default value is "undefined"

### ISSUE THREAD

**Issue by Piero93** [BlinkTagInc/node-gtfs#77]
skipDelete default value is "undefined" if not specified in config.json file, while in the readme file is specified that default value is "true".

` const task = {
      exclude: agency.exclude,
      agency_key: agency.agency_key,
      agency_url: agency.url,
      path: agency.path,
      downloadDir: path.resolve('./downloads'),
      db,
      skipDelete: config.skipDelete,
      log: (message, overwrite) => {
        log(`${overwrite !== true ? '\n' : ''}${task.agency_key}: ${message}`);
      }
    };`

`// Override using --skipDelete command line argument or `skipDelete` in config.json
    if (task.skipDelete) {
      task.log('Skipping deletion of existing data');
    } else {
      await removeDatabase(task);
    }`

**Comment by brendannee** [comment]
Thanks for pointing this out - you are right that the readme is consistent.

I just pushed an update that corrects this in the README, so `skipDelete` is by default `false`.
