### ISSUE TITLE
GTFS's dependency cannot find 'fs' module 

### ISSUE THREAD

**Issue by saothienhat** [BlinkTagInc/node-gtfs#80]
Hi all, 
Currently I using the GTFS latest version but I got an issue that is GTFS require 'extract-zip' module, and the 'extract-zip' module require 'fs' module which is no longer used. So,  how can I resolve this dependency issue ?

**Comment by brendannee** [comment]
What version of node.js are you using?

**Comment by saothienhat** [comment]
I using Node 8.x and GTFS 1.1.0. The GTFS 1.1.0 requires 'fs-extra' module instead of 'fs' module. But its dependencies such as 'extract-zip' require 'fs'

**Comment by brendannee** [comment]
Can you post the error message you are seeing? The 'fs' module is part of node.js core so shoudln't be a problem as a requirement.

**Comment by saothienhat** [comment]
Sorry, it is my wrong code. So, Please ignore this issue. Thank for your support
