### ISSUE TITLE
gtfs.getStops() throws Mongoose DeprecationWarning

### ISSUE THREAD

**Issue by Kenny806** [BlinkTagInc/node-gtfs#82]
Hi, I tried creating a simple example that would download my local agency's timetables and just print the available stops to console. I set mongoose.promise in my code, but still get a warning when I call gtfs.getStops(). My code is:

```
const config = require('./config.json');
const gtfs = require('gtfs');
var mongo = require('mongodb');
var mongoose = require('mongoose');

mongoose.Promise = global.Promise;

mongoose.connect(config.mongoUrl, {useMongoClient: true}).then(function() {
    console.log('connected')
    gtfs.getStops({
        agency_key: 'dpp'
    })
    .then(stops => {
        console.log(stops);
    });
}).catch(err => console.log(err));

```
config.json:
```
{
  "mongoUrl": "mongodb://localhost:27017/gtfs",
  "agencies": [
    {
      "agency_key": "dpp",
      "url": "http://opendata.iprpraha.cz/DPP/JR/jrdata.zip"
    }
  ]
}
```

I am using mongoose 4.11.8 and I ran gtfs.import and it reported no errors, and I did not find any problems in the db either. I found [this issue](https://github.com/Automattic/mongoose/issues/4951) on mongoose github and it seems there is a workaround, but it would require inserting 
`mongoose.promise = global.Promise`
into almost every file that accesses the db, including gtfs files. Have you encountered this issue before or do you have any more feasible workaround?

Thanks

**Comment by brendannee** [comment]
This happens when your project has mongoose installed twice - once as a
dependency of your project and once as a dependency of node-gtfs.

Is mongoose specified as a dependency of your project in package.json or is
it installed globally?

**Comment by Kenny806** [comment]
Thanks, that helped!

It was specified as a dependency in my package.json. I removed it, reinstalled node_modules and now it works fine. 

The only slight issue is, that when I want to access mongoose in my project, I have to require the one installed as a dependency of node-gtfs. Like this:
`const mongoose = require('./node_modules/gtfs/node_modules/mongoose');`
Is there a nicer way to do that?

**Comment by brendannee** [comment]
It is ok to specify it as a dependency in your project as long as you
specify the exact same version as node-GTFS and don’t use ^ or ~ in front
of it. Then, delete node_modules and npm install. NPM should realize that
it only needs to install one copy of mongoose.
