### ISSUE TITLE
Required parameter stop_id for getStoptimes()

### ISSUE THREAD

**Issue by Pathen85** [BlinkTagInc/node-gtfs#84]
Hello,

first I would like to thank you for your very good work here! The import and several queries worked instantly and just as expected.
However, I noticed that the function getStoptimes() needs the stop_id as a required parameter. In my case I would like to query for all stoptimes for a specific trip. So the parameter stop_id won't let me do this easily.
Maybe I am missing something here and I am sure there was a reason for you to make stop_id required, but in my case I don't want to filter for that, but only for the trip_id instead.
Thanks!

**Comment by brendannee** [comment]
Good point - this doesn't really need to be required.

I pushed a new version https://github.com/BlinkTagInc/node-gtfs/releases/tag/1.1.2 to NPM that allows you to query without a stop_id - try it out and let me know what you think.

**Comment by Pathen85** [comment]
Thanks alot!
