### ISSUE TITLE
Feature Request: GTFS-realtime support

### ISSUE THREAD

**Issue by mwickman** [BlinkTagInc/node-gtfs#86]
Love this project, thank you for making it available!

In my opinion, one great extension would be to add support for GTFS-realtime (https://developers.google.com/transit/gtfs-realtime/). I'm happy to start developing those features myself but thought it wise to check if you already have similar functionality in progress for this or another library. I'm still fairly new to the Transit domain so perhaps there are challenges with GTFS-realtime that I'm still not aware of.

Would GTFS-realtime support be in scope for this library?

**Comment by brendannee** [comment]
Great idea - I haven’t planned any work on GTFS real-time, so I’d be
interested in your thoughts on how it would work and what it all would do.
Perhaps a good way to start is figure out what the readme/documentation
would look like for this. Then, we can figure out how best to implement
this.

**Comment by mwickman** [comment]
Sounds like a good approach to me! I've taken a quick stab at some docs here https://github.com/BlinkTagInc/node-gtfs/pull/87

In summary, I think one could use the same configuration file and a different method name to poll whichever GTFS-realtime providers you want, and then add that data to existing models.

**Comment by brendannee** [comment]
Thanks for taking a stab at documenting this idea.

What are the advantages of implementing gtfs-realtime support in this library, vs creating a new library (node-gtfs-realtime) for this feature?

I haven't worked with gtfs-realtime much, so I haven't thought through all of the use cases.

Regarding youd documentation pull request, can you give me an example of what the method `gtfs.importRealtime` would return?

**Comment by Dashing-Nelson** [comment]
hey, has this feature been implemented?

**Comment by brendannee** [comment]
@Dashing-Nelson No it has not been implemented yet - it is just in the idea phase.

**Comment by brendannee** [comment]
I recently released https://github.com/BlinkTagInc/transit-arrivals-widget which is a library built on top of node-gtfs that pulls in GTFS-RT and creates a realtime arrival widget like the one on the homepage of  https://marintransit.org/.

I'm closing this issue for now but all feedback and suggestions on node-gtfs and transit-arrivals-widget are welcome.
