### ISSUE TITLE
Handle leading whitespace in GTFS data

### ISSUE THREAD

**Issue by markongithub** [BlinkTagInc/node-gtfs#89]
The trips.txt file from Chicago's Metra looks like this:
```
trip_id, arrival_time, departure_time, stop_id, stop_sequence, pickup_type, drop_off_type, center_boarding, south_boarding, bikes_allowed, notice
BNSF_BN1200_V1_A,  04:30:00,  04:30:00,  AURORA,  1,  0,  0,  0,  0,  1,  0
```

The calendar.txt file from Philadelphia's SEPTA rail division looks like this:
```
service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date
M1, 1, 1, 1, 1, 1, 0, 0, 20170910, 20180113
```

node-gtfs doesn't let me import and query either of them, because of the leading whitespace. I started special-casing those agencies and issuing special queries, but then I realized that Metra was even worse than I thought.

Would it be possible for node-gtfs to strip leading whitespace from all the field names and values?

**Comment by brendannee** [comment]
Great catch.

I just pushed an update to node-gtfs 1.4.0 that will handle whitespace in field names so these agencies should now work.

Try it out and let me know if you find any issues.

**Comment by markongithub** [comment]
Yes, SEPTA and Metra now work perfectly after re-importing. Thanks!
