### ISSUE TITLE
Cannot use gtfs's gets methods

### ISSUE THREAD

**Issue by danydacosta** [BlinkTagInc/node-gtfs#92]
Hello, 

I'm new to mongodb and I have struggle to fetch gtfs from my mondodb database using the gtfs library. Here is what I've done so far :

Installed node-gtfs using npm and importing my gtfs data using this config file :

```
{
  "mongoUrl": "mongodb://localhost:27017/gtfs_swiss",
  "agencies": [
    {
      "agency_key": "gtfs_swiss",
      "url": "https://opentransportdata.swiss/dataset/b408f747-9838-4c05-bb98-10dac3996f17/resource/ec665c51-122a-47e7-9fb9-3df88cead4eb/download/gtfsfp20182018-02-28.zip"
    }
  ]
}
```

run the `gtfs-import` successfully filled my database.

Then I created a nodejs server in order to do some tests :

```
const express = require("express");
const app = express();
const port = process.env.PORT || 5656;

const gtfs = require('gtfs');
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/gtfs_swiss');

// routes go here
app.get('/', (req, res) => {
    gtfs.getAgencies()
    .then(agencies => {
        console.log('success')
        // Do something with the array of `agencies`
    })
    .catch(err => {
        console.log('error')
    });
})

app.listen(port, () => {
    console.log(`http://localhost:${port}`)
})
```

But when I access my server with the port 5656, it goes to an infinite page loading. After some tests I figured out that the server was stuck in the `getAgencies` method. I don't think it's a problem between nodejs and mongodb as when I run my server using `node server.js`, I get an answer in the mongo output when it connects with `mongoose.connect('mongodb://localhost:27017/gtfs_swiss');
` .

Below is my mongod version :

```
db version v3.6.2
git version: 489d177dbd0f0420a8ca04d39fd78d0a2c539420
OpenSSL version: OpenSSL 1.0.1u-fips  22 Sep 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: 2008plus-ssl
    distarch: x86_64
    target_arch: x86_64
``` 

I tried with others `get`s methods with no success. Thanks for the help in advance!

**Comment by danydacosta** [comment]
Didn't get the issue running on OSX.

**Comment by brendannee** [comment]
OK - so on OS X your script works as expected, but  on windows it didn't work?

You might just be missing a response - see `res.json(agencies)`.

```
// routes go here
app.get('/', (req, res) => {
    gtfs.getAgencies()
    .then(agencies => {
        console.log('success')
        res.json(agencies);
        // Do something with the array of `agencies`
    })
    .catch(err => {
        console.log('error')
    });
})

```
