### ISSUE TITLE
Conditional GTFS import

### ISSUE THREAD

**Issue by andreasvirkus** [BlinkTagInc/node-gtfs#94]
Hello again,

This might sound stupid since I lack any real knowledge of GTFS, but I'm wondering if there's any way to only import the GTFS fields that have a zone name with a specific prefix (either from an array of prefixes or a wildcard like `['Harju1', 'Harju2']` or `Harju*`)?

Reason I'm asking is that the only GTFS available to me is country-wide (even though I specify my agency_key with the capital's name, but the GTFS doesn't seem to respect that really, using it in
other town's and cities' routes, stops, etc.)

If not, then is it possible to use it as a mongoose find filter within my queries (the 3rd parameter as I understood)? This last question may be more suitable for StackOverflow, so feel free to close if the first option isn't available and I'll do my best to find a way to handle this on the query level.

BR,
Andreas

**Comment by brendannee** [comment]
The library currently doesn't support limiting what gets imported, but that could be added as a feature. Can you link me to the GTFS file you are importing? Does it have multiple agencies in one file, or is it just one gigantic agency?

After import, you can query only for specific stops or routes - can you let me know more about the type of query you want to do? By zone, do you mean fare zone as defined in stops.txt? https://developers.google.com/transit/gtfs/reference/#stopstxt

**Comment by andreasvirkus** [comment]
The GTFS: http://peatus.ee/gtfs/gtfs.zip
It seems to be a gigantic agency (although they should be stated as multiple agencies imo).

Hmm... By zone I meant `zone_name`, as you can see in the query results here:
https://tallinn-transport-api.herokuapp.com/api/stops/center (might need to give Heroku some time to spin up). Some of them have `Harju1`, the rest aren't actually for the city I need (although the `agency_key` is still the same :/ )

> Can you let me know more about the type of query you want to do?
I have an idea for an app which will display the last transit times for a specific route or stop.
Currently when the app spins up, I simply list the central stops. When a user clicks on one,
I'd like to query the last time for all routes (and both directions) for that stop id.

**Comment by brendannee** [comment]
Thanks for the details.

`zone_name` doesn't seem to be a standard field in GTFS - so it would be up to you to filter on this field. You could update the schema for stops: https://github.com/BlinkTagInc/node-gtfs/blob/master/models/gtfs/stop.js and maintain your own that supports the additional fields in your feed, such as "zone_name". If these fields were defined in the schema, you could more easily query for them.

Or, you could write a small pre-import script that went through the GTFS file and removed all of the stops, routes and stoptimes that you were not interested in and created a smaller GTFS file for you to import.

**Comment by andreasvirkus** [comment]
I think the small separate pre-import script seems like the way to go, wouldn't want to locally override anything in this lib.

If it's not too much trouble, could you guide me in the right direction with how I'd go about querying the last departure time for a given stop_id (we can say for any route and I'll most likely figure out how to list all routes/directions for that given stop).

**Comment by brendannee** [comment]
You can get all stoptimes for a specific stop id like:

```
gtfs.getStoptimes({
  agency_key: 'caltrain',
  stop_id: '70011'
})
.then(stoptimes => {
  // loop through all stoptimes and find the latest one
});
```
