### ISSUE TITLE
gtfs-import: Post Processing data error

### ISSUE THREAD

**Issue by marcroiglama** [BlinkTagInc/node-gtfs#98]
Hi,

thank you very match for this useful software! 

I succesfully load some gtfs files from transitfeed, but I'm on trouble with The Netherlands gtfs file [http://transitfeeds.com/p/ov/814/latest](url). As this gtfs is huge, I do some preprocessing using python and pandas to filter it to Amsterdam scope, after filtering I get the same gtfs format without the stops and shapes that are outside Amsterdam. Gtfs-import Is throwing the following error after it finishes importing all txt files: 

`Amsterdam: Post Processing data
Error: { MongoError: Can't extract geo keys: { _id: ObjectId('5c177d639ac13d7de6ee17f8'), agency_id: "WPD", agency_name: "Wagenborg", agency_url: "http://www.wpd.nl/", agency_timezone: "Europe/Amsterdam", agency_phone: "0031881031000", agency_key: "Amsterdam", agency_bounds: { sw: [], ne: [] }, agency_center: [ nan.0, nan.0 ], date_last_updated: 1545043397966.0 }  Point coordinates must be finite numbers
    at Function.create (/home/muvadmin/.npm-global/lib/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:43:12)
    at toError (/home/muvadmin/.npm-global/lib/node_modules/mongoose/node_modules/mongodb/lib/utils.js:149:22)
    at coll.s.topology.update (/home/muvadmin/.npm-global/lib/node_modules/mongoose/node_modules/mongodb/lib/operations/collection_ops.js:1370:39)
    at /home/muvadmin/.npm-global/lib/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
  driver: true,
  name: 'MongoError',
  index: 0,
  code: 16755,
  errmsg:
   `Can't extract geo keys: { _id: ObjectId('5c177d639ac13d7de6ee17f8'), agency_id: "WPD", agency_name: "Wagenborg", agency_url: "http://www.wpd.nl/", agency_timezone: "Europe/Amsterdam", agency_phone: "0031881031000", agency_key: "Amsterdam", agency_bounds: { sw: [], ne: [] }, agency_center: [ nan.0, nan.0 ], date_last_updated: 1545043397966.0 }  Point coordinates must be finite numbers`,
  [Symbol(mongoErrorContextSymbol)]: {} }
`

In any case, my preprocessing doesn't perform any action on agencies.txt, which is the one seems to be problematic. I would like to know where the agency bounds does it comes from and what is the purpouse of this field. Maybe a solution can be to comment the code that performs this action?

Thank you in advance!

**Comment by marcroiglama** [comment]
There you go http://transitfeeds.com/p/ov/814/latest

**Comment by brendannee** [comment]
This looks like the original huge GTFS - can you send me the filtered version you are using that is just Amsterdam?

**Comment by marcroiglama** [comment]
You are right, sorry. Actually, I find my fault, I wasn't filtering the gtfs correctly and I was losing the geo data of files like stops.txt and so on. I fix this preprocessing issue and now is working perfectly. By my understanding I guess that the agency bounds is comming from other files geo data. Anyway, I would like to know what is purpose of this field and how is calculated. Thanks!

**Comment by brendannee** [comment]
I created the agency_bounds field as an easy way to query agencies - so this gets calculated based on all of the stops within an agency. If no stops have geo data, then it fails (but geo data is required to be valid GTFS).

Let me know if you have other questions, feature requests or ideas for improvements - pull requests welcome!
