### ISSUE TITLE
Query stop_times between hour range

### ISSUE THREAD

**Issue by sbehrends** [BlinkTagInc/node-gtfs#99]
While implementing a query to the stop_time model I wanted to add a conditional to select only the stop_times for a stop between to hours (example from 10:00 to 10:15).

Since arrival_time and departure_time are stored as string, the query will be complicated.

A solution would be to store departure as a timestamp from midnight (00:00)

```
StopTime.find({
    stop_id: req.params.stop_id,
    arrival_time: {
        $gt:  '10:00:00',
        $lt:  '10:15:00'
    }
}
```

**Comment by sbehrends** [comment]
Just created a PR for this feature.
Let me know if there is any feedback.

Cheers

**Comment by brendannee** [comment]
Wow - this is a great pull request and a very valuable feature.

I haven't had the need to query for specific times yet (I'm often just getting all times for a specific route and day) but adding these fields in very valuable.

I ran the tests and published an updated version with your changes. https://github.com/BlinkTagInc/node-gtfs/releases/tag/1.7.0

Let me know if you see other ways to improve the library or think of features it is missing.
